### ISSUE TITLE
Failed to load image error

### ISSUE THREAD

**Issue by aknight2015** [7thSamurai/steganography#3]
I'm running this on Debian Linux CLI. I compiled according to your guide. When I tried a test encode, copying and pasting the command from readme.md, I got a failed to load image error.

**Comment by 7thSamurai** [comment]
Did you just copy and paste the exact command and not change anything? If so, you need to copy the data directory to the build directory, or update the paths in the command to be "../data/" instead of "data/"

**Comment by aknight2015** [comment]
that did it.

**Comment by 7thSamurai** [comment]
Great!
