### ISSUE TITLE
Add ability to encode a text string

### ISSUE THREAD

**Issue by ghost** [7thSamurai/steganography#4]
This could enable users to just hide a quick text without having to write that text to a file first, then specify that file.

Maybe an option `-t`, `--text`.

**Comment by 7thSamurai** [comment]
Hello,

My sincere apologies that this has taken me almost a year to respond to. I've not been very active on here as of late...

Unfortunately I'm not interested in implementing this functionality at the moment. As of right now I only plan/want to support encoding files.

Alternatively, I would suggest just using `echo` and piping the output to a file. Example:

```
$ echo "Hello World!" > message.txt
``` 

And then encode `message.txt` as normal.
