### ISSUE TITLE
Please do not make encryption in  program  as mandatory option 

### ISSUE THREAD

**Issue by bulcsu202002** [7thSamurai/steganography#5]
I would not like to always encrypt what I hide in the picture because I usually hide already encrypted texts

**Comment by 7thSamurai** [comment]
Hello,

Sorry for the delay it took me to respond, I've not been very active on here as of late...

I'm not interested in making encryption optional, but for your case I'd suggest just not supplying a password. Either by just hitting the enter-key when the password prompt comes up, or by using the command-line options `-p ""` or `--passwd ""`.

*Note: Supplying a blank password at the password prompt used to not be possible, I just added that capability in commit 89d82da*
